#if BUILD_SERVER
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: war_message.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Sofunny.BiuBiuBiu2.Grpc {
  public static partial class WarServer
  {
    static readonly string __ServiceName = "warserver.WarServer";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sofunny.BiuBiuBiu2.Grpc.PostDataReq> __Marshaller_warserver_PostDataReq = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sofunny.BiuBiuBiu2.Grpc.PostDataReq.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sofunny.BiuBiuBiu2.Grpc.PostDataResp> __Marshaller_warserver_PostDataResp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sofunny.BiuBiuBiu2.Grpc.PostDataResp.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sofunny.BiuBiuBiu2.Grpc.CommonData> __Marshaller_warserver_CommonData = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sofunny.BiuBiuBiu2.Grpc.CommonData.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsReq> __Marshaller_warserver_GetFreeRoomsReq = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsReq.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsResp> __Marshaller_warserver_GetFreeRoomsResp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsResp.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumReq> __Marshaller_warserver_GetFreeRoomNumReq = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumReq.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumResp> __Marshaller_warserver_GetFreeRoomNumResp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumResp.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sofunny.BiuBiuBiu2.Grpc.PostDataReq, global::Sofunny.BiuBiuBiu2.Grpc.PostDataResp> __Method_PostData = new grpc::Method<global::Sofunny.BiuBiuBiu2.Grpc.PostDataReq, global::Sofunny.BiuBiuBiu2.Grpc.PostDataResp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PostData",
        __Marshaller_warserver_PostDataReq,
        __Marshaller_warserver_PostDataResp);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sofunny.BiuBiuBiu2.Grpc.CommonData, global::Sofunny.BiuBiuBiu2.Grpc.CommonData> __Method_BidStream = new grpc::Method<global::Sofunny.BiuBiuBiu2.Grpc.CommonData, global::Sofunny.BiuBiuBiu2.Grpc.CommonData>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "BidStream",
        __Marshaller_warserver_CommonData,
        __Marshaller_warserver_CommonData);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsReq, global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsResp> __Method_GetFreeRooms = new grpc::Method<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsReq, global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsResp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetFreeRooms",
        __Marshaller_warserver_GetFreeRoomsReq,
        __Marshaller_warserver_GetFreeRoomsResp);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumReq, global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumResp> __Method_GetFreeRoomNum = new grpc::Method<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumReq, global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumResp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetFreeRoomNum",
        __Marshaller_warserver_GetFreeRoomNumReq,
        __Marshaller_warserver_GetFreeRoomNumResp);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Sofunny.BiuBiuBiu2.Grpc.WarMessageReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of WarServer</summary>
    [grpc::BindServiceMethod(typeof(WarServer), "BindService")]
    public abstract partial class WarServerBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Sofunny.BiuBiuBiu2.Grpc.PostDataResp> PostData(global::Sofunny.BiuBiuBiu2.Grpc.PostDataReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task BidStream(grpc::IAsyncStreamReader<global::Sofunny.BiuBiuBiu2.Grpc.CommonData> requestStream, grpc::IServerStreamWriter<global::Sofunny.BiuBiuBiu2.Grpc.CommonData> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsResp> GetFreeRooms(global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumResp> GetFreeRoomNum(global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for WarServer</summary>
    public partial class WarServerClient : grpc::ClientBase<WarServerClient>
    {
      /// <summary>Creates a new client for WarServer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public WarServerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for WarServer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public WarServerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected WarServerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected WarServerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sofunny.BiuBiuBiu2.Grpc.PostDataResp PostData(global::Sofunny.BiuBiuBiu2.Grpc.PostDataReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PostData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sofunny.BiuBiuBiu2.Grpc.PostDataResp PostData(global::Sofunny.BiuBiuBiu2.Grpc.PostDataReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PostData, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sofunny.BiuBiuBiu2.Grpc.PostDataResp> PostDataAsync(global::Sofunny.BiuBiuBiu2.Grpc.PostDataReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PostDataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sofunny.BiuBiuBiu2.Grpc.PostDataResp> PostDataAsync(global::Sofunny.BiuBiuBiu2.Grpc.PostDataReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PostData, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Sofunny.BiuBiuBiu2.Grpc.CommonData, global::Sofunny.BiuBiuBiu2.Grpc.CommonData> BidStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BidStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Sofunny.BiuBiuBiu2.Grpc.CommonData, global::Sofunny.BiuBiuBiu2.Grpc.CommonData> BidStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_BidStream, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsResp GetFreeRooms(global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFreeRooms(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsResp GetFreeRooms(global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetFreeRooms, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsResp> GetFreeRoomsAsync(global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFreeRoomsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsResp> GetFreeRoomsAsync(global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetFreeRooms, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumResp GetFreeRoomNum(global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFreeRoomNum(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumResp GetFreeRoomNum(global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetFreeRoomNum, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumResp> GetFreeRoomNumAsync(global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFreeRoomNumAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumResp> GetFreeRoomNumAsync(global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetFreeRoomNum, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override WarServerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WarServerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(WarServerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_PostData, serviceImpl.PostData)
          .AddMethod(__Method_BidStream, serviceImpl.BidStream)
          .AddMethod(__Method_GetFreeRooms, serviceImpl.GetFreeRooms)
          .AddMethod(__Method_GetFreeRoomNum, serviceImpl.GetFreeRoomNum).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, WarServerBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_PostData, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Sofunny.BiuBiuBiu2.Grpc.PostDataReq, global::Sofunny.BiuBiuBiu2.Grpc.PostDataResp>(serviceImpl.PostData));
      serviceBinder.AddMethod(__Method_BidStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Sofunny.BiuBiuBiu2.Grpc.CommonData, global::Sofunny.BiuBiuBiu2.Grpc.CommonData>(serviceImpl.BidStream));
      serviceBinder.AddMethod(__Method_GetFreeRooms, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsReq, global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomsResp>(serviceImpl.GetFreeRooms));
      serviceBinder.AddMethod(__Method_GetFreeRoomNum, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumReq, global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomNumResp>(serviceImpl.GetFreeRoomNum));
    }

  }
  public static partial class WarGrpcServer
  {
    static readonly string __ServiceName = "warserver.WarGrpcServer";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sofunny.BiuBiuBiu2.Grpc.CommonData> __Marshaller_warserver_CommonData = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sofunny.BiuBiuBiu2.Grpc.CommonData.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomReq> __Marshaller_warserver_GetFreeRoomReq = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomReq.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomResp> __Marshaller_warserver_GetFreeRoomResp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomResp.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoReq> __Marshaller_warserver_GetWarRoomInfoReq = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoReq.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoResp> __Marshaller_warserver_GetWarRoomInfoResp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoResp.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sofunny.BiuBiuBiu2.Grpc.CommonData, global::Sofunny.BiuBiuBiu2.Grpc.CommonData> __Method_Notify = new grpc::Method<global::Sofunny.BiuBiuBiu2.Grpc.CommonData, global::Sofunny.BiuBiuBiu2.Grpc.CommonData>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Notify",
        __Marshaller_warserver_CommonData,
        __Marshaller_warserver_CommonData);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomReq, global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomResp> __Method_GetFreeRoom = new grpc::Method<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomReq, global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomResp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetFreeRoom",
        __Marshaller_warserver_GetFreeRoomReq,
        __Marshaller_warserver_GetFreeRoomResp);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoReq, global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoResp> __Method_GetWarRoomInfo = new grpc::Method<global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoReq, global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoResp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetWarRoomInfo",
        __Marshaller_warserver_GetWarRoomInfoReq,
        __Marshaller_warserver_GetWarRoomInfoResp);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Sofunny.BiuBiuBiu2.Grpc.WarMessageReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of WarGrpcServer</summary>
    [grpc::BindServiceMethod(typeof(WarGrpcServer), "BindService")]
    public abstract partial class WarGrpcServerBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Sofunny.BiuBiuBiu2.Grpc.CommonData> Notify(global::Sofunny.BiuBiuBiu2.Grpc.CommonData request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomResp> GetFreeRoom(global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoResp> GetWarRoomInfo(global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for WarGrpcServer</summary>
    public partial class WarGrpcServerClient : grpc::ClientBase<WarGrpcServerClient>
    {
      /// <summary>Creates a new client for WarGrpcServer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public WarGrpcServerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for WarGrpcServer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public WarGrpcServerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected WarGrpcServerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected WarGrpcServerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sofunny.BiuBiuBiu2.Grpc.CommonData Notify(global::Sofunny.BiuBiuBiu2.Grpc.CommonData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Notify(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sofunny.BiuBiuBiu2.Grpc.CommonData Notify(global::Sofunny.BiuBiuBiu2.Grpc.CommonData request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Notify, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sofunny.BiuBiuBiu2.Grpc.CommonData> NotifyAsync(global::Sofunny.BiuBiuBiu2.Grpc.CommonData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return NotifyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sofunny.BiuBiuBiu2.Grpc.CommonData> NotifyAsync(global::Sofunny.BiuBiuBiu2.Grpc.CommonData request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Notify, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomResp GetFreeRoom(global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFreeRoom(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomResp GetFreeRoom(global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetFreeRoom, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomResp> GetFreeRoomAsync(global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFreeRoomAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomResp> GetFreeRoomAsync(global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetFreeRoom, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoResp GetWarRoomInfo(global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWarRoomInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoResp GetWarRoomInfo(global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetWarRoomInfo, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoResp> GetWarRoomInfoAsync(global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWarRoomInfoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoResp> GetWarRoomInfoAsync(global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetWarRoomInfo, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override WarGrpcServerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WarGrpcServerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(WarGrpcServerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Notify, serviceImpl.Notify)
          .AddMethod(__Method_GetFreeRoom, serviceImpl.GetFreeRoom)
          .AddMethod(__Method_GetWarRoomInfo, serviceImpl.GetWarRoomInfo).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, WarGrpcServerBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Notify, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Sofunny.BiuBiuBiu2.Grpc.CommonData, global::Sofunny.BiuBiuBiu2.Grpc.CommonData>(serviceImpl.Notify));
      serviceBinder.AddMethod(__Method_GetFreeRoom, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomReq, global::Sofunny.BiuBiuBiu2.Grpc.GetFreeRoomResp>(serviceImpl.GetFreeRoom));
      serviceBinder.AddMethod(__Method_GetWarRoomInfo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoReq, global::Sofunny.BiuBiuBiu2.Grpc.GetWarRoomInfoResp>(serviceImpl.GetWarRoomInfo));
    }

  }
}
#endregion
#endif