// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: advertisement.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sofunny.BiuBiuBiu2.Protocol.Advertisement {

  /// <summary>Holder for reflection information generated from advertisement.proto</summary>
  public static partial class AdvertisementReflection {

    #region Descriptor
    /// <summary>File descriptor for advertisement.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AdvertisementReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNhZHZlcnRpc2VtZW50LnByb3RvEg1hZHZlcnRpc2VtZW50Ggxjb21tb24u",
            "cHJvdG8iKAoXR2V0RGFpbHlXYXRjaEFkc0NvdW50SW4SDQoFYWRfaWQYASAB",
            "KAUiRwoYR2V0RGFpbHlXYXRjaEFkc0NvdW50T3V0Eg0KBWNvdW50GAEgASgF",
            "Eg0KBWxpbWl0GAIgASgFEg0KBWFkX2lkGAMgASgFIi4KCldhdGNoQWRzSW4S",
            "DQoFYWRfaWQYASABKAUSEQoJdGFyZ2V0X2lkGAIgASgJIrsBCgtXYXRjaEFk",
            "c091dBItCgZzdGF0dXMYASABKA4yHS5hZHZlcnRpc2VtZW50LldhdGNoQWRz",
            "U3RhdHVzEg0KBWFkX2lkGAIgASgFEikKB3Jld2FyZHMYAyADKAsyGC5jb21t",
            "b24uQ2hhbmdlZEl0ZW1FbnRyeRIcChRxdWlja19jb21iaW5lX2V4cGlyZRgF",
            "IAEoAxIlCh1xdWlja19jb21iaW5lX3VubG9ja19kdXJhdGlvbhgGIAEoAyJY",
            "Ch5Ob3RpZnlFeHBpcmVXZWFwb25BZHNSZXdhcmRPdXQSDQoFYWRfaWQYASAB",
            "KAUSDwoHaXRlbV9pZBgCIAEoBRIWCg5jb3JlX3Jld2FyZF9pZBgDIAEoBSqV",
            "AQoOV2F0Y2hBZHNTdGF0dXMSHAoYV0FUQ0hfQURTX1NUQVRVU19TVUNDRUVE",
            "EAASGwoXV0FUQ0hfQURTX1NUQVRVU19GQUlMRUQQARIhCh1XQVRDSF9BRFNf",
            "U1RBVFVTX0FEX05PVF9GT1VORBACEiUKIVdBVENIX0FEU19TVEFUVVNfQURf",
            "TElNSVRfUkVBQ0hFRBADQnZaSGdpdC50dWJlL3NhdXNhZ2UtbWFuMi9nYW1l",
            "LXNlcnZlci9wcm90b3MvYWR2ZXJ0aXNlbWVudHBiO2FkdmVydGlzZW1lbnRw",
            "YqoCKVNvZnVubnkuQml1Qml1Qml1Mi5Qcm90b2NvbC5BZHZlcnRpc2VtZW50",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Sofunny.BiuBiuBiu2.Protocol.Common.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.WatchAdsStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.GetDailyWatchAdsCountIn), global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.GetDailyWatchAdsCountIn.Parser, new[]{ "AdId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.GetDailyWatchAdsCountOut), global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.GetDailyWatchAdsCountOut.Parser, new[]{ "Count", "Limit", "AdId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.WatchAdsIn), global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.WatchAdsIn.Parser, new[]{ "AdId", "TargetId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.WatchAdsOut), global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.WatchAdsOut.Parser, new[]{ "Status", "AdId", "Rewards", "QuickCombineExpire", "QuickCombineUnlockDuration" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.NotifyExpireWeaponAdsRewardOut), global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.NotifyExpireWeaponAdsRewardOut.Parser, new[]{ "AdId", "ItemId", "CoreRewardId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum WatchAdsStatus {
    /// <summary>
    /// 看广告成功
    /// </summary>
    [pbr::OriginalName("WATCH_ADS_STATUS_SUCCEED")] Succeed = 0,
    /// <summary>
    /// 看广告失败
    /// </summary>
    [pbr::OriginalName("WATCH_ADS_STATUS_FAILED")] Failed = 1,
    /// <summary>
    /// 广告不存在
    /// </summary>
    [pbr::OriginalName("WATCH_ADS_STATUS_AD_NOT_FOUND")] AdNotFound = 2,
    /// <summary>
    /// 广告播放次数已达到上限
    /// </summary>
    [pbr::OriginalName("WATCH_ADS_STATUS_AD_LIMIT_REACHED")] AdLimitReached = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 获取当日的看广告次数
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetDailyWatchAdsCountIn : pb::IMessage<GetDailyWatchAdsCountIn>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetDailyWatchAdsCountIn> _parser = new pb::MessageParser<GetDailyWatchAdsCountIn>(() => new GetDailyWatchAdsCountIn());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetDailyWatchAdsCountIn> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.AdvertisementReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetDailyWatchAdsCountIn() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetDailyWatchAdsCountIn(GetDailyWatchAdsCountIn other) : this() {
      adId_ = other.adId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetDailyWatchAdsCountIn Clone() {
      return new GetDailyWatchAdsCountIn(this);
    }

    /// <summary>Field number for the "ad_id" field.</summary>
    public const int AdIdFieldNumber = 1;
    private int adId_;
    /// <summary>
    /// ads_watch 表的 ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AdId {
      get { return adId_; }
      set {
        adId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetDailyWatchAdsCountIn);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetDailyWatchAdsCountIn other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AdId != other.AdId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AdId != 0) hash ^= AdId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AdId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AdId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AdId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AdId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AdId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AdId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetDailyWatchAdsCountIn other) {
      if (other == null) {
        return;
      }
      if (other.AdId != 0) {
        AdId = other.AdId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AdId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AdId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetDailyWatchAdsCountOut : pb::IMessage<GetDailyWatchAdsCountOut>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetDailyWatchAdsCountOut> _parser = new pb::MessageParser<GetDailyWatchAdsCountOut>(() => new GetDailyWatchAdsCountOut());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetDailyWatchAdsCountOut> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.AdvertisementReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetDailyWatchAdsCountOut() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetDailyWatchAdsCountOut(GetDailyWatchAdsCountOut other) : this() {
      count_ = other.count_;
      limit_ = other.limit_;
      adId_ = other.adId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetDailyWatchAdsCountOut Clone() {
      return new GetDailyWatchAdsCountOut(this);
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 1;
    private int count_;
    /// <summary>
    /// 当日看过的次数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "limit" field.</summary>
    public const int LimitFieldNumber = 2;
    private int limit_;
    /// <summary>
    /// 当日看广告次数上限
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Limit {
      get { return limit_; }
      set {
        limit_ = value;
      }
    }

    /// <summary>Field number for the "ad_id" field.</summary>
    public const int AdIdFieldNumber = 3;
    private int adId_;
    /// <summary>
    /// ads_watch 表的 ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AdId {
      get { return adId_; }
      set {
        adId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetDailyWatchAdsCountOut);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetDailyWatchAdsCountOut other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Count != other.Count) return false;
      if (Limit != other.Limit) return false;
      if (AdId != other.AdId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Count != 0) hash ^= Count.GetHashCode();
      if (Limit != 0) hash ^= Limit.GetHashCode();
      if (AdId != 0) hash ^= AdId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Count != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Count);
      }
      if (Limit != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Limit);
      }
      if (AdId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AdId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Count != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Count);
      }
      if (Limit != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Limit);
      }
      if (AdId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AdId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Count);
      }
      if (Limit != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Limit);
      }
      if (AdId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AdId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetDailyWatchAdsCountOut other) {
      if (other == null) {
        return;
      }
      if (other.Count != 0) {
        Count = other.Count;
      }
      if (other.Limit != 0) {
        Limit = other.Limit;
      }
      if (other.AdId != 0) {
        AdId = other.AdId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Count = input.ReadInt32();
            break;
          }
          case 16: {
            Limit = input.ReadInt32();
            break;
          }
          case 24: {
            AdId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Count = input.ReadInt32();
            break;
          }
          case 16: {
            Limit = input.ReadInt32();
            break;
          }
          case 24: {
            AdId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 看广告
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WatchAdsIn : pb::IMessage<WatchAdsIn>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WatchAdsIn> _parser = new pb::MessageParser<WatchAdsIn>(() => new WatchAdsIn());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WatchAdsIn> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.AdvertisementReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchAdsIn() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchAdsIn(WatchAdsIn other) : this() {
      adId_ = other.adId_;
      targetId_ = other.targetId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchAdsIn Clone() {
      return new WatchAdsIn(this);
    }

    /// <summary>Field number for the "ad_id" field.</summary>
    public const int AdIdFieldNumber = 1;
    private int adId_;
    /// <summary>
    /// ads_watch 表的 ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AdId {
      get { return adId_; }
      set {
        adId_ = value;
      }
    }

    /// <summary>Field number for the "target_id" field.</summary>
    public const int TargetIdFieldNumber = 2;
    private string targetId_ = "";
    /// <summary>
    /// war_id / 宝箱 ID / 物品 ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TargetId {
      get { return targetId_; }
      set {
        targetId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WatchAdsIn);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WatchAdsIn other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AdId != other.AdId) return false;
      if (TargetId != other.TargetId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AdId != 0) hash ^= AdId.GetHashCode();
      if (TargetId.Length != 0) hash ^= TargetId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AdId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AdId);
      }
      if (TargetId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AdId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AdId);
      }
      if (TargetId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AdId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AdId);
      }
      if (TargetId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WatchAdsIn other) {
      if (other == null) {
        return;
      }
      if (other.AdId != 0) {
        AdId = other.AdId;
      }
      if (other.TargetId.Length != 0) {
        TargetId = other.TargetId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AdId = input.ReadInt32();
            break;
          }
          case 18: {
            TargetId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AdId = input.ReadInt32();
            break;
          }
          case 18: {
            TargetId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WatchAdsOut : pb::IMessage<WatchAdsOut>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WatchAdsOut> _parser = new pb::MessageParser<WatchAdsOut>(() => new WatchAdsOut());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WatchAdsOut> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.AdvertisementReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchAdsOut() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchAdsOut(WatchAdsOut other) : this() {
      status_ = other.status_;
      adId_ = other.adId_;
      rewards_ = other.rewards_.Clone();
      quickCombineExpire_ = other.quickCombineExpire_;
      quickCombineUnlockDuration_ = other.quickCombineUnlockDuration_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchAdsOut Clone() {
      return new WatchAdsOut(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.WatchAdsStatus status_ = global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.WatchAdsStatus.Succeed;
    /// <summary>
    /// 看广告返回状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.WatchAdsStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "ad_id" field.</summary>
    public const int AdIdFieldNumber = 2;
    private int adId_;
    /// <summary>
    /// ads_watch 表的 ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AdId {
      get { return adId_; }
      set {
        adId_ = value;
      }
    }

    /// <summary>Field number for the "rewards" field.</summary>
    public const int RewardsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry> _repeated_rewards_codec
        = pb::FieldCodec.ForMessage(26, global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry.Parser);
    private readonly pbc::RepeatedField<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry> rewards_ = new pbc::RepeatedField<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry>();
    /// <summary>
    /// 奖励
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry> Rewards {
      get { return rewards_; }
    }

    /// <summary>Field number for the "quick_combine_expire" field.</summary>
    public const int QuickCombineExpireFieldNumber = 5;
    private long quickCombineExpire_;
    /// <summary>
    /// 一键合成过期时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long QuickCombineExpire {
      get { return quickCombineExpire_; }
      set {
        quickCombineExpire_ = value;
      }
    }

    /// <summary>Field number for the "quick_combine_unlock_duration" field.</summary>
    public const int QuickCombineUnlockDurationFieldNumber = 6;
    private long quickCombineUnlockDuration_;
    /// <summary>
    /// 一键合成解锁多久显示（策划配置/弹窗提示）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long QuickCombineUnlockDuration {
      get { return quickCombineUnlockDuration_; }
      set {
        quickCombineUnlockDuration_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WatchAdsOut);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WatchAdsOut other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (AdId != other.AdId) return false;
      if(!rewards_.Equals(other.rewards_)) return false;
      if (QuickCombineExpire != other.QuickCombineExpire) return false;
      if (QuickCombineUnlockDuration != other.QuickCombineUnlockDuration) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.WatchAdsStatus.Succeed) hash ^= Status.GetHashCode();
      if (AdId != 0) hash ^= AdId.GetHashCode();
      hash ^= rewards_.GetHashCode();
      if (QuickCombineExpire != 0L) hash ^= QuickCombineExpire.GetHashCode();
      if (QuickCombineUnlockDuration != 0L) hash ^= QuickCombineUnlockDuration.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Status != global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.WatchAdsStatus.Succeed) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (AdId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(AdId);
      }
      rewards_.WriteTo(output, _repeated_rewards_codec);
      if (QuickCombineExpire != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(QuickCombineExpire);
      }
      if (QuickCombineUnlockDuration != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(QuickCombineUnlockDuration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Status != global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.WatchAdsStatus.Succeed) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (AdId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(AdId);
      }
      rewards_.WriteTo(ref output, _repeated_rewards_codec);
      if (QuickCombineExpire != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(QuickCombineExpire);
      }
      if (QuickCombineUnlockDuration != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(QuickCombineUnlockDuration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Status != global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.WatchAdsStatus.Succeed) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (AdId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AdId);
      }
      size += rewards_.CalculateSize(_repeated_rewards_codec);
      if (QuickCombineExpire != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(QuickCombineExpire);
      }
      if (QuickCombineUnlockDuration != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(QuickCombineUnlockDuration);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WatchAdsOut other) {
      if (other == null) {
        return;
      }
      if (other.Status != global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.WatchAdsStatus.Succeed) {
        Status = other.Status;
      }
      if (other.AdId != 0) {
        AdId = other.AdId;
      }
      rewards_.Add(other.rewards_);
      if (other.QuickCombineExpire != 0L) {
        QuickCombineExpire = other.QuickCombineExpire;
      }
      if (other.QuickCombineUnlockDuration != 0L) {
        QuickCombineUnlockDuration = other.QuickCombineUnlockDuration;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.WatchAdsStatus) input.ReadEnum();
            break;
          }
          case 16: {
            AdId = input.ReadInt32();
            break;
          }
          case 26: {
            rewards_.AddEntriesFrom(input, _repeated_rewards_codec);
            break;
          }
          case 40: {
            QuickCombineExpire = input.ReadInt64();
            break;
          }
          case 48: {
            QuickCombineUnlockDuration = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Status = (global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.WatchAdsStatus) input.ReadEnum();
            break;
          }
          case 16: {
            AdId = input.ReadInt32();
            break;
          }
          case 26: {
            rewards_.AddEntriesFrom(ref input, _repeated_rewards_codec);
            break;
          }
          case 40: {
            QuickCombineExpire = input.ReadInt64();
            break;
          }
          case 48: {
            QuickCombineUnlockDuration = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 推送武器过期广告奖励
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NotifyExpireWeaponAdsRewardOut : pb::IMessage<NotifyExpireWeaponAdsRewardOut>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NotifyExpireWeaponAdsRewardOut> _parser = new pb::MessageParser<NotifyExpireWeaponAdsRewardOut>(() => new NotifyExpireWeaponAdsRewardOut());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NotifyExpireWeaponAdsRewardOut> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sofunny.BiuBiuBiu2.Protocol.Advertisement.AdvertisementReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifyExpireWeaponAdsRewardOut() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifyExpireWeaponAdsRewardOut(NotifyExpireWeaponAdsRewardOut other) : this() {
      adId_ = other.adId_;
      itemId_ = other.itemId_;
      coreRewardId_ = other.coreRewardId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifyExpireWeaponAdsRewardOut Clone() {
      return new NotifyExpireWeaponAdsRewardOut(this);
    }

    /// <summary>Field number for the "ad_id" field.</summary>
    public const int AdIdFieldNumber = 1;
    private int adId_;
    /// <summary>
    /// ads_watch 表的 ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AdId {
      get { return adId_; }
      set {
        adId_ = value;
      }
    }

    /// <summary>Field number for the "item_id" field.</summary>
    public const int ItemIdFieldNumber = 2;
    private int itemId_;
    /// <summary>
    /// 过期的物品 ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ItemId {
      get { return itemId_; }
      set {
        itemId_ = value;
      }
    }

    /// <summary>Field number for the "core_reward_id" field.</summary>
    public const int CoreRewardIdFieldNumber = 3;
    private int coreRewardId_;
    /// <summary>
    /// 奖励配置主表 ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CoreRewardId {
      get { return coreRewardId_; }
      set {
        coreRewardId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NotifyExpireWeaponAdsRewardOut);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NotifyExpireWeaponAdsRewardOut other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AdId != other.AdId) return false;
      if (ItemId != other.ItemId) return false;
      if (CoreRewardId != other.CoreRewardId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AdId != 0) hash ^= AdId.GetHashCode();
      if (ItemId != 0) hash ^= ItemId.GetHashCode();
      if (CoreRewardId != 0) hash ^= CoreRewardId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AdId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AdId);
      }
      if (ItemId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ItemId);
      }
      if (CoreRewardId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CoreRewardId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AdId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AdId);
      }
      if (ItemId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ItemId);
      }
      if (CoreRewardId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CoreRewardId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AdId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AdId);
      }
      if (ItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemId);
      }
      if (CoreRewardId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CoreRewardId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NotifyExpireWeaponAdsRewardOut other) {
      if (other == null) {
        return;
      }
      if (other.AdId != 0) {
        AdId = other.AdId;
      }
      if (other.ItemId != 0) {
        ItemId = other.ItemId;
      }
      if (other.CoreRewardId != 0) {
        CoreRewardId = other.CoreRewardId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AdId = input.ReadInt32();
            break;
          }
          case 16: {
            ItemId = input.ReadInt32();
            break;
          }
          case 24: {
            CoreRewardId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AdId = input.ReadInt32();
            break;
          }
          case 16: {
            ItemId = input.ReadInt32();
            break;
          }
          case 24: {
            CoreRewardId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
