//
// THIS FILE IS GENERATED BY protocol
// DO NOT MODIFY BY MANUAL
//
using System;
using Sofunny.BiuBiuBiu2.GameServerMessage;
namespace Sofunny.BiuBiuBiu2.Protocol {
    public class Protocol : IProtocol {
        Player.Player player;
        Match.Match match;
        Equip.Equip equip;
        Rank.Rank rank;
        Leaderboard.Leaderboard leaderboard;
        RedPoint.RedPoint redPoint;
        Mail.Mail mail;
        War.War war;
        Level.Level level;
        Task.Task task;
        Advertisement.Advertisement advertisement;
        Shop.Shop shop;
        Item.Item item;
        public Protocol() {
            player = new Player.Player();
            match = new Match.Match();
            equip = new Equip.Equip();
            rank = new Rank.Rank();
            leaderboard = new Leaderboard.Leaderboard();
            redPoint = new RedPoint.RedPoint();
            mail = new Mail.Mail();
            war = new War.War();
            level = new Level.Level();
            task = new Task.Task();
            advertisement = new Advertisement.Advertisement();
            shop = new Shop.Shop();
            item = new Item.Item();
        }
        public IMessage NewRequest(byte serviceID, byte messageID) {
            switch (serviceID) {
                case 0:
                    return player.NewRequest(messageID);
                case 1:
                    return match.NewRequest(messageID);
                case 2:
                    return equip.NewRequest(messageID);
                case 3:
                    return rank.NewRequest(messageID);
                case 4:
                    return leaderboard.NewRequest(messageID);
                case 5:
                    return redPoint.NewRequest(messageID);
                case 6:
                    return mail.NewRequest(messageID);
                case 7:
                    return war.NewRequest(messageID);
                case 8:
                    return level.NewRequest(messageID);
                case 9:
                    return task.NewRequest(messageID);
                case 14:
                    return advertisement.NewRequest(messageID);
                case 15:
                    return shop.NewRequest(messageID);
                case 16:
                    return item.NewRequest(messageID);
                default:
                    throw new NotImplementedException("Unknown Service ID");
            }
        }
        public IMessage NewResponse(byte serviceID, byte messageID) {
            switch (serviceID) {
                case 0:
                    return player.NewResponse(messageID);
                case 1:
                    return match.NewResponse(messageID);
                case 2:
                    return equip.NewResponse(messageID);
                case 3:
                    return rank.NewResponse(messageID);
                case 4:
                    return leaderboard.NewResponse(messageID);
                case 5:
                    return redPoint.NewResponse(messageID);
                case 6:
                    return mail.NewResponse(messageID);
                case 7:
                    return war.NewResponse(messageID);
                case 8:
                    return level.NewResponse(messageID);
                case 9:
                    return task.NewResponse(messageID);
                case 14:
                    return advertisement.NewResponse(messageID);
                case 15:
                    return shop.NewResponse(messageID);
                case 16:
                    return item.NewResponse(messageID);
                default:
                    throw new NotImplementedException("Unknown Service ID");
            }
        }
        public static String GetIdentityFromType(IMessage message) {
			return message.Identity();
        }
    }
}
