// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rank.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sofunny.BiuBiuBiu2.Protocol.Rank {

  /// <summary>Holder for reflection information generated from rank.proto</summary>
  public static partial class RankReflection {

    #region Descriptor
    /// <summary>File descriptor for rank.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RankReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpyYW5rLnByb3RvEgRyYW5rGgxjb21tb24ucHJvdG8igQEKEFNlYXNvblNl",
            "dHRsZURhdGESEQoJc2Vhc29uX2lkGAEgASgFEhcKD2xhc3RfcmFua19zY29y",
            "ZRgCIAEoBRIWCg5uZXdfcmFua19zY29yZRgDIAEoBRIpCgdyZXdhcmRzGAQg",
            "AygLMhguY29tbW9uLkNoYW5nZWRJdGVtRW50cnkiDAoKUmFua0luZm9JbiLN",
            "AQoLUmFua0luZm9PdXQSEgoKcmFua19zY29yZRgBIAEoBRIRCglzZWFzb25f",
            "aWQYAiABKAUSFgoOdGFrZWRfcmFua19pZHMYAyADKAUSEwoLY3VyX3Jhbmtp",
            "bmcYBCABKAUSFwoPY2hhbmdlZF9yYW5raW5nGAUgASgFEhwKFHNlYXNvbl9o",
            "aWdoZXN0X3Njb3JlGAYgASgFEhoKEmhpc3RvcnlfcmFua19zY29yZRgHIAEo",
            "BRIXCg9zZWFzb25fZW5kX3RpbWUYCCABKAMiIgoPR2V0UmFua1Jld2FyZElu",
            "Eg8KB3JhbmtfaWQYASABKAUiaAoQR2V0UmFua1Jld2FyZE91dBIpCgZzdGF0",
            "dXMYASABKA4yGS5yYW5rLkdldFJhbmtSZXdhcmRTdGF0dXMSKQoHcmV3YXJk",
            "cxgCIAMoCzIYLmNvbW1vbi5DaGFuZ2VkSXRlbUVudHJ5Ij4KFU5vdGlmeVNl",
            "YXNvblNldHRsZU91dBIlCgVkYXRhcxgBIAMoCzIWLnJhbmsuU2Vhc29uU2V0",
            "dGxlRGF0YSJhChNOb3RpZnlSYW5rU2V0dGxlT3V0EhcKD2xhc3RfcmFua19z",
            "Y29yZRgBIAEoBRIVCg1jaGFuZ2VkX3Njb3JlGAIgASgFEhoKEmhpc3Rvcnlf",
            "cmFua19zY29yZRgDIAEoBSJTChNOb3RpZnlSYW5rVW5sb2NrT3V0EhEKCXVu",
            "bG9ja19pZBgBIAMoBRIpCgdyZXdhcmRzGAIgAygLMhguY29tbW9uLkNoYW5n",
            "ZWRJdGVtRW50cnkqswEKE0dldFJhbmtSZXdhcmRTdGF0dXMSIgoeR0VUX1JB",
            "TktfUkVXQVJEX1NUQVRVU19TVUNDRVNTEAASHwobR0VUX1JBTktfUkVXQVJE",
            "X1NUQVRVU19GQUlMEAESKgomR0VUX1JBTktfUkVXQVJEX1NUQVRVU19JTlZB",
            "TElEX1JBTktfSUQQAhIrCidHRVRfUkFOS19SRVdBUkRfU1RBVFVTX1JBTktf",
            "QUxSRUFEWV9HT1QQA0JbWjZnaXQudHViZS9zYXVzYWdlLW1hbjIvZ2FtZS1z",
            "ZXJ2ZXIvcHJvdG9zL3JhbmtwYjtyYW5rcGKqAiBTb2Z1bm55LkJpdUJpdUJp",
            "dTIuUHJvdG9jb2wuUmFua2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Sofunny.BiuBiuBiu2.Protocol.Common.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Sofunny.BiuBiuBiu2.Protocol.Rank.GetRankRewardStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Sofunny.BiuBiuBiu2.Protocol.Rank.SeasonSettleData), global::Sofunny.BiuBiuBiu2.Protocol.Rank.SeasonSettleData.Parser, new[]{ "SeasonId", "LastRankScore", "NewRankScore", "Rewards" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sofunny.BiuBiuBiu2.Protocol.Rank.RankInfoIn), global::Sofunny.BiuBiuBiu2.Protocol.Rank.RankInfoIn.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sofunny.BiuBiuBiu2.Protocol.Rank.RankInfoOut), global::Sofunny.BiuBiuBiu2.Protocol.Rank.RankInfoOut.Parser, new[]{ "RankScore", "SeasonId", "TakedRankIds", "CurRanking", "ChangedRanking", "SeasonHighestScore", "HistoryRankScore", "SeasonEndTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sofunny.BiuBiuBiu2.Protocol.Rank.GetRankRewardIn), global::Sofunny.BiuBiuBiu2.Protocol.Rank.GetRankRewardIn.Parser, new[]{ "RankId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sofunny.BiuBiuBiu2.Protocol.Rank.GetRankRewardOut), global::Sofunny.BiuBiuBiu2.Protocol.Rank.GetRankRewardOut.Parser, new[]{ "Status", "Rewards" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sofunny.BiuBiuBiu2.Protocol.Rank.NotifySeasonSettleOut), global::Sofunny.BiuBiuBiu2.Protocol.Rank.NotifySeasonSettleOut.Parser, new[]{ "Datas" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sofunny.BiuBiuBiu2.Protocol.Rank.NotifyRankSettleOut), global::Sofunny.BiuBiuBiu2.Protocol.Rank.NotifyRankSettleOut.Parser, new[]{ "LastRankScore", "ChangedScore", "HistoryRankScore" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sofunny.BiuBiuBiu2.Protocol.Rank.NotifyRankUnlockOut), global::Sofunny.BiuBiuBiu2.Protocol.Rank.NotifyRankUnlockOut.Parser, new[]{ "UnlockId", "Rewards" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum GetRankRewardStatus {
    /// <summary>
    /// 成功
    /// </summary>
    [pbr::OriginalName("GET_RANK_REWARD_STATUS_SUCCESS")] Success = 0,
    /// <summary>
    /// 失败
    /// </summary>
    [pbr::OriginalName("GET_RANK_REWARD_STATUS_FAIL")] Fail = 1,
    /// <summary>
    /// 无效的段位ID(请求参数有问题)
    /// </summary>
    [pbr::OriginalName("GET_RANK_REWARD_STATUS_INVALID_RANK_ID")] InvalidRankId = 2,
    /// <summary>
    /// 该段位已经领取
    /// </summary>
    [pbr::OriginalName("GET_RANK_REWARD_STATUS_RANK_ALREADY_GOT")] RankAlreadyGot = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 赛季结算数据
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SeasonSettleData : pb::IMessage<SeasonSettleData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SeasonSettleData> _parser = new pb::MessageParser<SeasonSettleData>(() => new SeasonSettleData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SeasonSettleData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sofunny.BiuBiuBiu2.Protocol.Rank.RankReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonSettleData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonSettleData(SeasonSettleData other) : this() {
      seasonId_ = other.seasonId_;
      lastRankScore_ = other.lastRankScore_;
      newRankScore_ = other.newRankScore_;
      rewards_ = other.rewards_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonSettleData Clone() {
      return new SeasonSettleData(this);
    }

    /// <summary>Field number for the "season_id" field.</summary>
    public const int SeasonIdFieldNumber = 1;
    private int seasonId_;
    /// <summary>
    /// 赛季id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeasonId {
      get { return seasonId_; }
      set {
        seasonId_ = value;
      }
    }

    /// <summary>Field number for the "last_rank_score" field.</summary>
    public const int LastRankScoreFieldNumber = 2;
    private int lastRankScore_;
    /// <summary>
    /// 玩家段位分数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LastRankScore {
      get { return lastRankScore_; }
      set {
        lastRankScore_ = value;
      }
    }

    /// <summary>Field number for the "new_rank_score" field.</summary>
    public const int NewRankScoreFieldNumber = 3;
    private int newRankScore_;
    /// <summary>
    /// 继承后的段位分数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NewRankScore {
      get { return newRankScore_; }
      set {
        newRankScore_ = value;
      }
    }

    /// <summary>Field number for the "rewards" field.</summary>
    public const int RewardsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry> _repeated_rewards_codec
        = pb::FieldCodec.ForMessage(34, global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry.Parser);
    private readonly pbc::RepeatedField<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry> rewards_ = new pbc::RepeatedField<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry>();
    /// <summary>
    /// 奖励列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry> Rewards {
      get { return rewards_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SeasonSettleData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SeasonSettleData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SeasonId != other.SeasonId) return false;
      if (LastRankScore != other.LastRankScore) return false;
      if (NewRankScore != other.NewRankScore) return false;
      if(!rewards_.Equals(other.rewards_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SeasonId != 0) hash ^= SeasonId.GetHashCode();
      if (LastRankScore != 0) hash ^= LastRankScore.GetHashCode();
      if (NewRankScore != 0) hash ^= NewRankScore.GetHashCode();
      hash ^= rewards_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SeasonId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SeasonId);
      }
      if (LastRankScore != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(LastRankScore);
      }
      if (NewRankScore != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NewRankScore);
      }
      rewards_.WriteTo(output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SeasonId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SeasonId);
      }
      if (LastRankScore != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(LastRankScore);
      }
      if (NewRankScore != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NewRankScore);
      }
      rewards_.WriteTo(ref output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SeasonId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeasonId);
      }
      if (LastRankScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LastRankScore);
      }
      if (NewRankScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NewRankScore);
      }
      size += rewards_.CalculateSize(_repeated_rewards_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SeasonSettleData other) {
      if (other == null) {
        return;
      }
      if (other.SeasonId != 0) {
        SeasonId = other.SeasonId;
      }
      if (other.LastRankScore != 0) {
        LastRankScore = other.LastRankScore;
      }
      if (other.NewRankScore != 0) {
        NewRankScore = other.NewRankScore;
      }
      rewards_.Add(other.rewards_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SeasonId = input.ReadInt32();
            break;
          }
          case 16: {
            LastRankScore = input.ReadInt32();
            break;
          }
          case 24: {
            NewRankScore = input.ReadInt32();
            break;
          }
          case 34: {
            rewards_.AddEntriesFrom(input, _repeated_rewards_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SeasonId = input.ReadInt32();
            break;
          }
          case 16: {
            LastRankScore = input.ReadInt32();
            break;
          }
          case 24: {
            NewRankScore = input.ReadInt32();
            break;
          }
          case 34: {
            rewards_.AddEntriesFrom(ref input, _repeated_rewards_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 玩家段位信息（段位主界面）
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RankInfoIn : pb::IMessage<RankInfoIn>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RankInfoIn> _parser = new pb::MessageParser<RankInfoIn>(() => new RankInfoIn());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RankInfoIn> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sofunny.BiuBiuBiu2.Protocol.Rank.RankReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RankInfoIn() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RankInfoIn(RankInfoIn other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RankInfoIn Clone() {
      return new RankInfoIn(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RankInfoIn);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RankInfoIn other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RankInfoIn other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RankInfoOut : pb::IMessage<RankInfoOut>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RankInfoOut> _parser = new pb::MessageParser<RankInfoOut>(() => new RankInfoOut());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RankInfoOut> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sofunny.BiuBiuBiu2.Protocol.Rank.RankReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RankInfoOut() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RankInfoOut(RankInfoOut other) : this() {
      rankScore_ = other.rankScore_;
      seasonId_ = other.seasonId_;
      takedRankIds_ = other.takedRankIds_.Clone();
      curRanking_ = other.curRanking_;
      changedRanking_ = other.changedRanking_;
      seasonHighestScore_ = other.seasonHighestScore_;
      historyRankScore_ = other.historyRankScore_;
      seasonEndTime_ = other.seasonEndTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RankInfoOut Clone() {
      return new RankInfoOut(this);
    }

    /// <summary>Field number for the "rank_score" field.</summary>
    public const int RankScoreFieldNumber = 1;
    private int rankScore_;
    /// <summary>
    /// 玩家段位分数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RankScore {
      get { return rankScore_; }
      set {
        rankScore_ = value;
      }
    }

    /// <summary>Field number for the "season_id" field.</summary>
    public const int SeasonIdFieldNumber = 2;
    private int seasonId_;
    /// <summary>
    /// 赛季id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeasonId {
      get { return seasonId_; }
      set {
        seasonId_ = value;
      }
    }

    /// <summary>Field number for the "taked_rank_ids" field.</summary>
    public const int TakedRankIdsFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_takedRankIds_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> takedRankIds_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 已经领取的段位奖励 ID 列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> TakedRankIds {
      get { return takedRankIds_; }
    }

    /// <summary>Field number for the "cur_ranking" field.</summary>
    public const int CurRankingFieldNumber = 4;
    private int curRanking_;
    /// <summary>
    /// 当前排名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CurRanking {
      get { return curRanking_; }
      set {
        curRanking_ = value;
      }
    }

    /// <summary>Field number for the "changed_ranking" field.</summary>
    public const int ChangedRankingFieldNumber = 5;
    private int changedRanking_;
    /// <summary>
    /// 相较于昨日的变化
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ChangedRanking {
      get { return changedRanking_; }
      set {
        changedRanking_ = value;
      }
    }

    /// <summary>Field number for the "season_highest_score" field.</summary>
    public const int SeasonHighestScoreFieldNumber = 6;
    private int seasonHighestScore_;
    /// <summary>
    /// 赛季最高分数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeasonHighestScore {
      get { return seasonHighestScore_; }
      set {
        seasonHighestScore_ = value;
      }
    }

    /// <summary>Field number for the "history_rank_score" field.</summary>
    public const int HistoryRankScoreFieldNumber = 7;
    private int historyRankScore_;
    /// <summary>
    /// 玩家历史最高段位分数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HistoryRankScore {
      get { return historyRankScore_; }
      set {
        historyRankScore_ = value;
      }
    }

    /// <summary>Field number for the "season_end_time" field.</summary>
    public const int SeasonEndTimeFieldNumber = 8;
    private long seasonEndTime_;
    /// <summary>
    /// 赛季结束时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SeasonEndTime {
      get { return seasonEndTime_; }
      set {
        seasonEndTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RankInfoOut);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RankInfoOut other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RankScore != other.RankScore) return false;
      if (SeasonId != other.SeasonId) return false;
      if(!takedRankIds_.Equals(other.takedRankIds_)) return false;
      if (CurRanking != other.CurRanking) return false;
      if (ChangedRanking != other.ChangedRanking) return false;
      if (SeasonHighestScore != other.SeasonHighestScore) return false;
      if (HistoryRankScore != other.HistoryRankScore) return false;
      if (SeasonEndTime != other.SeasonEndTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RankScore != 0) hash ^= RankScore.GetHashCode();
      if (SeasonId != 0) hash ^= SeasonId.GetHashCode();
      hash ^= takedRankIds_.GetHashCode();
      if (CurRanking != 0) hash ^= CurRanking.GetHashCode();
      if (ChangedRanking != 0) hash ^= ChangedRanking.GetHashCode();
      if (SeasonHighestScore != 0) hash ^= SeasonHighestScore.GetHashCode();
      if (HistoryRankScore != 0) hash ^= HistoryRankScore.GetHashCode();
      if (SeasonEndTime != 0L) hash ^= SeasonEndTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RankScore != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RankScore);
      }
      if (SeasonId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SeasonId);
      }
      takedRankIds_.WriteTo(output, _repeated_takedRankIds_codec);
      if (CurRanking != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CurRanking);
      }
      if (ChangedRanking != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ChangedRanking);
      }
      if (SeasonHighestScore != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SeasonHighestScore);
      }
      if (HistoryRankScore != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(HistoryRankScore);
      }
      if (SeasonEndTime != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(SeasonEndTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RankScore != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RankScore);
      }
      if (SeasonId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SeasonId);
      }
      takedRankIds_.WriteTo(ref output, _repeated_takedRankIds_codec);
      if (CurRanking != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CurRanking);
      }
      if (ChangedRanking != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ChangedRanking);
      }
      if (SeasonHighestScore != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SeasonHighestScore);
      }
      if (HistoryRankScore != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(HistoryRankScore);
      }
      if (SeasonEndTime != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(SeasonEndTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RankScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RankScore);
      }
      if (SeasonId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeasonId);
      }
      size += takedRankIds_.CalculateSize(_repeated_takedRankIds_codec);
      if (CurRanking != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurRanking);
      }
      if (ChangedRanking != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChangedRanking);
      }
      if (SeasonHighestScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeasonHighestScore);
      }
      if (HistoryRankScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HistoryRankScore);
      }
      if (SeasonEndTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SeasonEndTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RankInfoOut other) {
      if (other == null) {
        return;
      }
      if (other.RankScore != 0) {
        RankScore = other.RankScore;
      }
      if (other.SeasonId != 0) {
        SeasonId = other.SeasonId;
      }
      takedRankIds_.Add(other.takedRankIds_);
      if (other.CurRanking != 0) {
        CurRanking = other.CurRanking;
      }
      if (other.ChangedRanking != 0) {
        ChangedRanking = other.ChangedRanking;
      }
      if (other.SeasonHighestScore != 0) {
        SeasonHighestScore = other.SeasonHighestScore;
      }
      if (other.HistoryRankScore != 0) {
        HistoryRankScore = other.HistoryRankScore;
      }
      if (other.SeasonEndTime != 0L) {
        SeasonEndTime = other.SeasonEndTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RankScore = input.ReadInt32();
            break;
          }
          case 16: {
            SeasonId = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            takedRankIds_.AddEntriesFrom(input, _repeated_takedRankIds_codec);
            break;
          }
          case 32: {
            CurRanking = input.ReadInt32();
            break;
          }
          case 40: {
            ChangedRanking = input.ReadInt32();
            break;
          }
          case 48: {
            SeasonHighestScore = input.ReadInt32();
            break;
          }
          case 56: {
            HistoryRankScore = input.ReadInt32();
            break;
          }
          case 64: {
            SeasonEndTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RankScore = input.ReadInt32();
            break;
          }
          case 16: {
            SeasonId = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            takedRankIds_.AddEntriesFrom(ref input, _repeated_takedRankIds_codec);
            break;
          }
          case 32: {
            CurRanking = input.ReadInt32();
            break;
          }
          case 40: {
            ChangedRanking = input.ReadInt32();
            break;
          }
          case 48: {
            SeasonHighestScore = input.ReadInt32();
            break;
          }
          case 56: {
            HistoryRankScore = input.ReadInt32();
            break;
          }
          case 64: {
            SeasonEndTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 领取段位奖励
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetRankRewardIn : pb::IMessage<GetRankRewardIn>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetRankRewardIn> _parser = new pb::MessageParser<GetRankRewardIn>(() => new GetRankRewardIn());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetRankRewardIn> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sofunny.BiuBiuBiu2.Protocol.Rank.RankReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRankRewardIn() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRankRewardIn(GetRankRewardIn other) : this() {
      rankId_ = other.rankId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRankRewardIn Clone() {
      return new GetRankRewardIn(this);
    }

    /// <summary>Field number for the "rank_id" field.</summary>
    public const int RankIdFieldNumber = 1;
    private int rankId_;
    /// <summary>
    /// 段位ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RankId {
      get { return rankId_; }
      set {
        rankId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetRankRewardIn);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetRankRewardIn other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RankId != other.RankId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RankId != 0) hash ^= RankId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RankId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RankId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RankId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RankId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RankId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RankId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetRankRewardIn other) {
      if (other == null) {
        return;
      }
      if (other.RankId != 0) {
        RankId = other.RankId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RankId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RankId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetRankRewardOut : pb::IMessage<GetRankRewardOut>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetRankRewardOut> _parser = new pb::MessageParser<GetRankRewardOut>(() => new GetRankRewardOut());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetRankRewardOut> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sofunny.BiuBiuBiu2.Protocol.Rank.RankReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRankRewardOut() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRankRewardOut(GetRankRewardOut other) : this() {
      status_ = other.status_;
      rewards_ = other.rewards_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRankRewardOut Clone() {
      return new GetRankRewardOut(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::Sofunny.BiuBiuBiu2.Protocol.Rank.GetRankRewardStatus status_ = global::Sofunny.BiuBiuBiu2.Protocol.Rank.GetRankRewardStatus.Success;
    /// <summary>
    /// 领取状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Sofunny.BiuBiuBiu2.Protocol.Rank.GetRankRewardStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "rewards" field.</summary>
    public const int RewardsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry> _repeated_rewards_codec
        = pb::FieldCodec.ForMessage(18, global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry.Parser);
    private readonly pbc::RepeatedField<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry> rewards_ = new pbc::RepeatedField<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry>();
    /// <summary>
    /// 奖励物列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry> Rewards {
      get { return rewards_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetRankRewardOut);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetRankRewardOut other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if(!rewards_.Equals(other.rewards_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != global::Sofunny.BiuBiuBiu2.Protocol.Rank.GetRankRewardStatus.Success) hash ^= Status.GetHashCode();
      hash ^= rewards_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Status != global::Sofunny.BiuBiuBiu2.Protocol.Rank.GetRankRewardStatus.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      rewards_.WriteTo(output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Status != global::Sofunny.BiuBiuBiu2.Protocol.Rank.GetRankRewardStatus.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      rewards_.WriteTo(ref output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Status != global::Sofunny.BiuBiuBiu2.Protocol.Rank.GetRankRewardStatus.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      size += rewards_.CalculateSize(_repeated_rewards_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetRankRewardOut other) {
      if (other == null) {
        return;
      }
      if (other.Status != global::Sofunny.BiuBiuBiu2.Protocol.Rank.GetRankRewardStatus.Success) {
        Status = other.Status;
      }
      rewards_.Add(other.rewards_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::Sofunny.BiuBiuBiu2.Protocol.Rank.GetRankRewardStatus) input.ReadEnum();
            break;
          }
          case 18: {
            rewards_.AddEntriesFrom(input, _repeated_rewards_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Status = (global::Sofunny.BiuBiuBiu2.Protocol.Rank.GetRankRewardStatus) input.ReadEnum();
            break;
          }
          case 18: {
            rewards_.AddEntriesFrom(ref input, _repeated_rewards_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 通知赛季结算
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NotifySeasonSettleOut : pb::IMessage<NotifySeasonSettleOut>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NotifySeasonSettleOut> _parser = new pb::MessageParser<NotifySeasonSettleOut>(() => new NotifySeasonSettleOut());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NotifySeasonSettleOut> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sofunny.BiuBiuBiu2.Protocol.Rank.RankReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifySeasonSettleOut() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifySeasonSettleOut(NotifySeasonSettleOut other) : this() {
      datas_ = other.datas_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifySeasonSettleOut Clone() {
      return new NotifySeasonSettleOut(this);
    }

    /// <summary>Field number for the "datas" field.</summary>
    public const int DatasFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Sofunny.BiuBiuBiu2.Protocol.Rank.SeasonSettleData> _repeated_datas_codec
        = pb::FieldCodec.ForMessage(10, global::Sofunny.BiuBiuBiu2.Protocol.Rank.SeasonSettleData.Parser);
    private readonly pbc::RepeatedField<global::Sofunny.BiuBiuBiu2.Protocol.Rank.SeasonSettleData> datas_ = new pbc::RepeatedField<global::Sofunny.BiuBiuBiu2.Protocol.Rank.SeasonSettleData>();
    /// <summary>
    /// 赛季结算数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Sofunny.BiuBiuBiu2.Protocol.Rank.SeasonSettleData> Datas {
      get { return datas_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NotifySeasonSettleOut);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NotifySeasonSettleOut other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!datas_.Equals(other.datas_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= datas_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      datas_.WriteTo(output, _repeated_datas_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      datas_.WriteTo(ref output, _repeated_datas_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += datas_.CalculateSize(_repeated_datas_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NotifySeasonSettleOut other) {
      if (other == null) {
        return;
      }
      datas_.Add(other.datas_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            datas_.AddEntriesFrom(input, _repeated_datas_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            datas_.AddEntriesFrom(ref input, _repeated_datas_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 通知玩家段位结算
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NotifyRankSettleOut : pb::IMessage<NotifyRankSettleOut>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NotifyRankSettleOut> _parser = new pb::MessageParser<NotifyRankSettleOut>(() => new NotifyRankSettleOut());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NotifyRankSettleOut> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sofunny.BiuBiuBiu2.Protocol.Rank.RankReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifyRankSettleOut() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifyRankSettleOut(NotifyRankSettleOut other) : this() {
      lastRankScore_ = other.lastRankScore_;
      changedScore_ = other.changedScore_;
      historyRankScore_ = other.historyRankScore_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifyRankSettleOut Clone() {
      return new NotifyRankSettleOut(this);
    }

    /// <summary>Field number for the "last_rank_score" field.</summary>
    public const int LastRankScoreFieldNumber = 1;
    private int lastRankScore_;
    /// <summary>
    /// 玩家之前的段位分数 （不包含本次变化的）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LastRankScore {
      get { return lastRankScore_; }
      set {
        lastRankScore_ = value;
      }
    }

    /// <summary>Field number for the "changed_score" field.</summary>
    public const int ChangedScoreFieldNumber = 2;
    private int changedScore_;
    /// <summary>
    /// 本次改变的分数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ChangedScore {
      get { return changedScore_; }
      set {
        changedScore_ = value;
      }
    }

    /// <summary>Field number for the "history_rank_score" field.</summary>
    public const int HistoryRankScoreFieldNumber = 3;
    private int historyRankScore_;
    /// <summary>
    /// 玩家历史最高段位分数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HistoryRankScore {
      get { return historyRankScore_; }
      set {
        historyRankScore_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NotifyRankSettleOut);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NotifyRankSettleOut other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LastRankScore != other.LastRankScore) return false;
      if (ChangedScore != other.ChangedScore) return false;
      if (HistoryRankScore != other.HistoryRankScore) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LastRankScore != 0) hash ^= LastRankScore.GetHashCode();
      if (ChangedScore != 0) hash ^= ChangedScore.GetHashCode();
      if (HistoryRankScore != 0) hash ^= HistoryRankScore.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LastRankScore != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(LastRankScore);
      }
      if (ChangedScore != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ChangedScore);
      }
      if (HistoryRankScore != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(HistoryRankScore);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LastRankScore != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(LastRankScore);
      }
      if (ChangedScore != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ChangedScore);
      }
      if (HistoryRankScore != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(HistoryRankScore);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LastRankScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LastRankScore);
      }
      if (ChangedScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChangedScore);
      }
      if (HistoryRankScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HistoryRankScore);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NotifyRankSettleOut other) {
      if (other == null) {
        return;
      }
      if (other.LastRankScore != 0) {
        LastRankScore = other.LastRankScore;
      }
      if (other.ChangedScore != 0) {
        ChangedScore = other.ChangedScore;
      }
      if (other.HistoryRankScore != 0) {
        HistoryRankScore = other.HistoryRankScore;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LastRankScore = input.ReadInt32();
            break;
          }
          case 16: {
            ChangedScore = input.ReadInt32();
            break;
          }
          case 24: {
            HistoryRankScore = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LastRankScore = input.ReadInt32();
            break;
          }
          case 16: {
            ChangedScore = input.ReadInt32();
            break;
          }
          case 24: {
            HistoryRankScore = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 通知段位解锁
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NotifyRankUnlockOut : pb::IMessage<NotifyRankUnlockOut>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NotifyRankUnlockOut> _parser = new pb::MessageParser<NotifyRankUnlockOut>(() => new NotifyRankUnlockOut());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NotifyRankUnlockOut> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sofunny.BiuBiuBiu2.Protocol.Rank.RankReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifyRankUnlockOut() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifyRankUnlockOut(NotifyRankUnlockOut other) : this() {
      unlockId_ = other.unlockId_.Clone();
      rewards_ = other.rewards_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifyRankUnlockOut Clone() {
      return new NotifyRankUnlockOut(this);
    }

    /// <summary>Field number for the "unlock_id" field.</summary>
    public const int UnlockIdFieldNumber = 1;
    private static readonly pb::FieldCodec<int> _repeated_unlockId_codec
        = pb::FieldCodec.ForInt32(10);
    private readonly pbc::RepeatedField<int> unlockId_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 解锁表 ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> UnlockId {
      get { return unlockId_; }
    }

    /// <summary>Field number for the "rewards" field.</summary>
    public const int RewardsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry> _repeated_rewards_codec
        = pb::FieldCodec.ForMessage(18, global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry.Parser);
    private readonly pbc::RepeatedField<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry> rewards_ = new pbc::RepeatedField<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry>();
    /// <summary>
    /// 奖励
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Sofunny.BiuBiuBiu2.Protocol.Common.ChangedItemEntry> Rewards {
      get { return rewards_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NotifyRankUnlockOut);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NotifyRankUnlockOut other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!unlockId_.Equals(other.unlockId_)) return false;
      if(!rewards_.Equals(other.rewards_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= unlockId_.GetHashCode();
      hash ^= rewards_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      unlockId_.WriteTo(output, _repeated_unlockId_codec);
      rewards_.WriteTo(output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      unlockId_.WriteTo(ref output, _repeated_unlockId_codec);
      rewards_.WriteTo(ref output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += unlockId_.CalculateSize(_repeated_unlockId_codec);
      size += rewards_.CalculateSize(_repeated_rewards_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NotifyRankUnlockOut other) {
      if (other == null) {
        return;
      }
      unlockId_.Add(other.unlockId_);
      rewards_.Add(other.rewards_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            unlockId_.AddEntriesFrom(input, _repeated_unlockId_codec);
            break;
          }
          case 18: {
            rewards_.AddEntriesFrom(input, _repeated_rewards_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            unlockId_.AddEntriesFrom(ref input, _repeated_unlockId_codec);
            break;
          }
          case 18: {
            rewards_.AddEntriesFrom(ref input, _repeated_rewards_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
