//
// THIS FILE IS GENERATED BY protocol
// DO NOT MODIFY BY MANUAL
//
using System;
using Sofunny.BiuBiuBiu2.GameServerMessage;
namespace Sofunny.BiuBiuBiu2.Protocol.Shop {
    public partial class Shop {
        public IMessage NewRequest(byte messageID) {
            switch (messageID) {
				case 0:
					return new GetExchangeShopInfoIn();
				case 1:
					return new BuyItemIn();
				case 3:
					return new ClientReqRefreshShopIn();
                default:
                    throw new NotImplementedException("Unknown Message ID");
            }
        }
        public IMessage NewResponse(byte messageID) {
            switch (messageID) {
				case 0:
					return new GetExchangeShopInfoOut();
				case 1:
					return new BuyItemOut();
				case 2:
					return new NotifyRandomGoodsOut();
				case 3:
					return new ClientReqRefreshShopOut();
                default:
                    throw new NotImplementedException("Unknown Message ID");
            }
        }
    }
    public partial class GetExchangeShopInfoIn : IMessage {
        public static byte ServiceId { get; }  = 15;
        public static byte MessageId { get; } = 0;
        public static String identity { get; } = "Shop.GetExchangeShopInfoIn";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class GetExchangeShopInfoOut : IMessage {
        public static byte ServiceId { get; }  = 15;
        public static byte MessageId { get; } = 0;
        public static String identity { get; } = "Shop.GetExchangeShopInfoOut";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class BuyItemIn : IMessage {
        public static byte ServiceId { get; }  = 15;
        public static byte MessageId { get; } = 1;
        public static String identity { get; } = "Shop.BuyItemIn";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class BuyItemOut : IMessage {
        public static byte ServiceId { get; }  = 15;
        public static byte MessageId { get; } = 1;
        public static String identity { get; } = "Shop.BuyItemOut";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class NotifyRandomGoodsOut : IMessage {
        public static byte ServiceId { get; }  = 15;
        public static byte MessageId { get; } = 2;
        public static String identity { get; } = "Shop.NotifyRandomGoodsOut";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class ClientReqRefreshShopIn : IMessage {
        public static byte ServiceId { get; }  = 15;
        public static byte MessageId { get; } = 3;
        public static String identity { get; } = "Shop.ClientReqRefreshShopIn";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class ClientReqRefreshShopOut : IMessage {
        public static byte ServiceId { get; }  = 15;
        public static byte MessageId { get; } = 3;
        public static String identity { get; } = "Shop.ClientReqRefreshShopOut";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
}
