//
// THIS FILE IS GENERATED BY protocol
// DO NOT MODIFY BY MANUAL
//
using System;
using Sofunny.BiuBiuBiu2.GameServerMessage;
namespace Sofunny.BiuBiuBiu2.Protocol.Task {
    public partial class Task {
        public IMessage NewRequest(byte messageID) {
            switch (messageID) {
				case 0:
					return new GetLevelTasksIn();
				case 1:
					return new GetProficiencyTasksIn();
				case 4:
					return new ClaimProficiencyTaskRewardIn();
				case 5:
					return new ClearLevelTaskNewFlagIn();
				case 6:
					return new ShareGameIn();
				case 7:
					return new RefreshLevelRoutineTaskIn();
                default:
                    throw new NotImplementedException("Unknown Message ID");
            }
        }
        public IMessage NewResponse(byte messageID) {
            switch (messageID) {
				case 0:
					return new GetLevelTasksOut();
				case 1:
					return new GetProficiencyTasksOut();
				case 2:
					return new NotifyLevelTaskProgressChangeOut();
				case 3:
					return new NotifyProficiencyTaskProgressChangeOut();
				case 4:
					return new ClaimProficiencyTaskRewardOut();
				case 5:
					return new ClearLevelTaskNewFlagOut();
				case 6:
					return new ShareGameOut();
				case 7:
					return new RefreshLevelRoutineTaskOut();
                default:
                    throw new NotImplementedException("Unknown Message ID");
            }
        }
    }
    public partial class GetLevelTasksIn : IMessage {
        public static byte ServiceId { get; }  = 9;
        public static byte MessageId { get; } = 0;
        public static String identity { get; } = "Task.GetLevelTasksIn";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class GetLevelTasksOut : IMessage {
        public static byte ServiceId { get; }  = 9;
        public static byte MessageId { get; } = 0;
        public static String identity { get; } = "Task.GetLevelTasksOut";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class GetProficiencyTasksIn : IMessage {
        public static byte ServiceId { get; }  = 9;
        public static byte MessageId { get; } = 1;
        public static String identity { get; } = "Task.GetProficiencyTasksIn";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class GetProficiencyTasksOut : IMessage {
        public static byte ServiceId { get; }  = 9;
        public static byte MessageId { get; } = 1;
        public static String identity { get; } = "Task.GetProficiencyTasksOut";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class NotifyLevelTaskProgressChangeOut : IMessage {
        public static byte ServiceId { get; }  = 9;
        public static byte MessageId { get; } = 2;
        public static String identity { get; } = "Task.NotifyLevelTaskProgressChangeOut";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class NotifyProficiencyTaskProgressChangeOut : IMessage {
        public static byte ServiceId { get; }  = 9;
        public static byte MessageId { get; } = 3;
        public static String identity { get; } = "Task.NotifyProficiencyTaskProgressChangeOut";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class ClaimProficiencyTaskRewardIn : IMessage {
        public static byte ServiceId { get; }  = 9;
        public static byte MessageId { get; } = 4;
        public static String identity { get; } = "Task.ClaimProficiencyTaskRewardIn";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class ClaimProficiencyTaskRewardOut : IMessage {
        public static byte ServiceId { get; }  = 9;
        public static byte MessageId { get; } = 4;
        public static String identity { get; } = "Task.ClaimProficiencyTaskRewardOut";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class ClearLevelTaskNewFlagIn : IMessage {
        public static byte ServiceId { get; }  = 9;
        public static byte MessageId { get; } = 5;
        public static String identity { get; } = "Task.ClearLevelTaskNewFlagIn";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class ClearLevelTaskNewFlagOut : IMessage {
        public static byte ServiceId { get; }  = 9;
        public static byte MessageId { get; } = 5;
        public static String identity { get; } = "Task.ClearLevelTaskNewFlagOut";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class ShareGameIn : IMessage {
        public static byte ServiceId { get; }  = 9;
        public static byte MessageId { get; } = 6;
        public static String identity { get; } = "Task.ShareGameIn";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class ShareGameOut : IMessage {
        public static byte ServiceId { get; }  = 9;
        public static byte MessageId { get; } = 6;
        public static String identity { get; } = "Task.ShareGameOut";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class RefreshLevelRoutineTaskIn : IMessage {
        public static byte ServiceId { get; }  = 9;
        public static byte MessageId { get; } = 7;
        public static String identity { get; } = "Task.RefreshLevelRoutineTaskIn";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
    public partial class RefreshLevelRoutineTaskOut : IMessage {
        public static byte ServiceId { get; }  = 9;
        public static byte MessageId { get; } = 7;
        public static String identity { get; } = "Task.RefreshLevelRoutineTaskOut";
        public byte ServiceID() {
            return ServiceId;
        }
        public byte MessageID() {
            return MessageId;
        }
        public String Identity() {
            return identity;
        }
    }
}
